### ISSUE TITLE
Random letters after groups named from templates 

### ISSUE THREAD

**Issue by JorgeR81** [aegis72/aegisflow_utility_nodes#1]
When I load a template, the new group name gets random letters and numbers after the template name.

In this example, this template was simply named "FaceID".

Is it to make sure group names are different ?

Why not just "FaceID_1", "FaceID_2", etc. ... ?

![template](https://github.com/aegis72/aegisflow_utility_nodes/assets/72734038/78336930-6e74-44ee-ae9b-6fcba3f350cd)

**Comment by aegis72** [comment]
Yes. This is to prevent broadcast clashes in Shima, and enumerating them wouldn't be a solution because of the non-linear way stuff can be created or removed and placed. We would need to increment, and track the incrementing, of each group as it was placed, as well as their function (IE, faceID vs KSampler, f/e) and then dynamically rename the groups. 

Simple 3 char randomization doesn't PREVENT clashes, because technically there's a 1 in ~47,000 chance of getting the same group name twice in a workflow. But it was enough to allow discrete targeting without having to write complex tracking of all the groups and managing them. 

Either way, you'd still have to target (or not) with a regex. So, if you don't need to care RE which face ID something is sent to, you can do .\*send1.\*, or .\*send1\\b (boundary). But if you DID need to, you'd do .\*send1.\*xw4 (or whatever).
